apiVersion: apps/v1
kind: Deployment
metadata:
    name: bearnaisee-api
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bearnaisee-api
    template:
        metadata:
            labels:
                app: bearnaisee-api
        spec:
            containers:
                - name: bearnaisee-api
                  image: hougesen/bearnaisee-api:master
                  ports:
                      - containerPort: 5000
                  env:
                      - name: PORT
                        value: '5000'
                      - name: NODE_ENV
                        value: 'production'
                      - name: POSTGRES_HOST
                        value: '207.154.212.57'
                      - name: POSTGRES_USER
                        value: 'postgres'
                      - name: POSTGRES_PASSWORD
                        value: 'lidlfanboys'
                      - name: POSTGRES_DB
                        value: 'bearnaisee'
