apiVersion: apps/v1
kind: Deployment
metadata:
    name: bearnaisee-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bearnaisee-app
    template:
        metadata:
            labels:
                app: bearnaisee-app
        spec:
            containers:
                - name: bearnaisee-app
                  image: hougesen/bearnaisee-app:master
                  ports:
                      - containerPort: 80
                  env:
                      - name: VUE_APP_API_URL
                        value: 'http://134.209.135.5:5000'
                      - name: VUE_APP_IMAGE_SERVICE
                        value: 'http://143.198.251.122:8000'
