apiVersion: v1
kind: Service
metadata:
    name: image-service-svc
    labels:
        app: image-service
spec:
    type: NodePort
    ports:
        - port: 8000
          targetPort: 80
          nodePort: 30085
    selector:
        app: image-service
